### ISSUE TITLE
Add this addon.

### ISSUE THREAD

**Issue by Melvovin** [yuwex/scratchcloud#3]
Can you add an addon that can show the cloud variables in our project please?

**Comment by yuwex** [comment]
This is actually built into scratchcloud! The `Client` object has an attribute called `cloud_variables`, which is a dictionary object with variable names and values. If no variables are found, the client will error, unless you set `ignore_missing_variables=True` when creating the client.

The client object is able to get these values because scratch is *supposed* to send all variables and their values whenever you connect to any project.

However, since I've been away from scratchcloud, scratch has updated their websocket server to be more unreliable about sending these values, which may cause the cloud cache to be empty. This is why, in many projects with cloud view counters, you can see the value being reset to 1 even though the value was much larger. Therefore, `Client.cloud_variables` is unreliable.

You could theoretically forcefully restart the websocket connection until you get the correct response, but that is a hassle, and is not something I plan to add to the library.

**Comment by Melvovin** [comment]
How to use scratchcloud?

**Comment by yuwex** [comment]
Read the tutorial here: https://yuwex.github.io/scratchcloud/basic_tutorial.html

Please only use this part of github if you find an issue on this library. For random questions, contact me on scratch :)
