### ISSUE TITLE
"No Cloud Variables Found"

### ISSUE THREAD

**Issue by AxizY** [yuwex/scratchcloud#4]
I am testing the demo example found in the tutorial and I'm getting the error:
"scratchcloud.errors.MissingCloudVariable: No Cloud Variables Found!"

I'm using the provided example project as well.
I'm not sure but could it be related to me not seeing 'cookies' popping up in the headers for the WebSocket in chrome dev tools?

**Comment by yuwex** [comment]
I haven't updated this library in a good while, and in that time, scratch changes how it handles cloud handshakes. Before, when connecting to a scratch project, scratch would guarantee a "handshake" with the client object containing a list of all of the cloud variables. If you connected to a project without any cloud variables, then scratch would tell you that the project you're connecting to doesn't have any variables.

Since I've been gone, scratch changed this system to be very unreliable. I haven't had the time to test it, but it seems like the influx of people using 3rd-party cloud librarys (like scratchcloud and scratchattach) caused scratch to change how cloud variables are handled—namely scratch doesn't always let the connected clients know what cloud variables exist.

You can fix this by passing `ignore_missing_variables=True` when creating a CloudClient.

```py

from scratchcloud import CloudClient

client = CloudClient(username='username', project_id='12345678', ignore_missing_variables=True)
```

Hope this helps. Let me know if you have further questions!
